### ISSUE TITLE
You can't use the result of an Observable as data source

### ISSUE THREAD

**Issue by skyfrk** [manishjanky/ngx-pagination-bootstrap#1]
If you use the result of an Observable and the result changes you have to call the function "changePageData()" at least once so that "calculateCurrentItemsRange()" gets executed, in order to get a  working pagination bar.

I hope you get what I want to say. Thank you for your work! @manishjanky

**Comment by manishjanky** [comment]
@Skyfr3ak Thanks for your inputs. Will surely look into this and resolve this. 
Thanks for your support :)

**Comment by manishjanky** [comment]
This has been fixed. Now you can use a Observable data source as well and it will recalculate the required properties.
Hence closing this.
